services:
  proxy:
    build:
      dockerfile: deploy/Dockerfile_nginx
      args:
        - NODE_ENV=local
    ports:
      - "443:443"
      - "80:80"
    restart: always
  nextjs:
    depends_on:
      - proxy
    build:
      dockerfile: deploy/Dockerfile_next
      args:
        - NODE_ENV=local
    restart: always
